### ISSUE TITLE
Error on dev server start

### ISSUE THREAD

**Issue by walnutfalls** [ft-interactive/koa2-typescript-boilerplate#2]
Thanks for the quick response to the last issue! 

I'm seeing this error when I start the dev server: 
{ Error: ENOENT: no such file or directory, open '.env'
    at Object.fs.openSync (fs.js:557:18)
    at Object.fs.readFileSync (fs.js:467:33)
    at Object.config (/home/concubicycle/dev/qualifiedclimatevoice/node_modules/dotenv/lib/main.js:30:37)
    at Object.<anonymous> (/home/concubicycle/dev/qualifiedclimatevoice/lib/index.ts:8:88)
    at Module._compile (module.js:573:32)
    at Module.m._compile (/home/concubicycle/dev/qualifiedclimatevoice/node_modules/ts-node/src/index.ts:406:23)
    at Module._extensions..js (module.js:582:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/home/concubicycle/dev/qualifiedclimatevoice/node_modules/ts-node/src/index.ts:409:12)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12) errno: -2, code: 'ENOENT', syscall: 'open', path: '.env' }

**Comment by aendra-rininsland** [comment]
@concubicycle Hi! Apologies for the delay, your issue got buried in my notifications. 😅 

You need to create a `.env` file inside the repo directory to store local environment variables in. You can also set `$NODE_ENV` to anything but `development` to disable `dotenv` and thus negate the need to create a `.env` file.
